// membrosData.js

const membros = [
    {
        id: 1,
        nome: 'Ana',
        sobrenome: 'Silva',
        idade: 23,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Rua 10',
        organizacao: 'Sociedade de Socorro',
        dataDeBatismo: '2008-07-20',
        descricao:
            'Voluntária ativa no projeto de serviço comunitário mensal. Ótima coordenadora de eventos.',
    },
    {
        id: 2,
        nome: 'Bruno',
        sobrenome: 'Santos',
        idade: 23,
        sexo: 'Masculino',
        endereco: 'Bairro Guarani, Av. Principal',
        organizacao: 'Quórum de Elderes',
        dataDeBatismo: '2008-09-10',
        descricao:
            'Especialista em TI. Ajuda com a manutenção do site da organização. Membro novo na ala.',
    },
    {
        id: 3,
        nome: 'Carla',
        sobrenome: 'Oliveira',
        idade: 23,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Bloco B',
        organizacao: 'Moças',
        dataDeBatismo: '2008-01-25',
        descricao:
            'Mudou-se recentemente para a cidade. Necessita de acompanhamento dos líderes.',
    },
    {
        id: 4,
        nome: 'Daniel',
        sobrenome: 'Pereira',
        idade: 10,
        sexo: 'Masculino',
        endereco: 'Bairro Guarani, Casa 5',
        organizacao: 'Primária',
        dataDeBatismo: '2023-03-18',
        descricao:
            'Adora cantar. Seus pais são membros da Sociedade de Socorro.',
    },
    {
        id: 5,
        nome: 'Eduarda',
        sobrenome: 'Costa',
        idade: 9,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Lote 12',
        organizacao: 'Primária',
        dataDeBatismo: '2024-01-14',
        descricao:
            'Muito interessada nas atividades da Primária. Seu aniversário é em Janeiro.',
    },
    {
        id: 6,
        nome: 'Felipe',
        sobrenome: 'Rodrigues',
        idade: 23,
        sexo: 'Masculino',
        endereco: 'Bairro Guarani, Apt 101',
        organizacao: 'Quórum de Elderes',
        dataDeBatismo: '2008-04-12',
        descricao:
            'Voluntário na manutenção da capela. Recém-formado em engenharia civil.',
    },
    {
        id: 7,
        nome: 'Gabriela',
        sobrenome: 'Almeida',
        idade: 23,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Praça da Árvore',
        organizacao: 'Sociedade de Socorro',
        dataDeBatismo: '2008-09-07',
        descricao:
            'Professora de música. Ajuda com o coral da organização. Frequência 100%.',
    },
    {
        id: 8,
        nome: 'Heitor',
        sobrenome: 'Nunes',
        idade: 23,
        sexo: 'Masculino',
        endereco: 'Bairro Guarani, Ed. Sol',
        organizacao: 'Quórum de Elderes',
        dataDeBatismo: '2008-06-01',
        descricao:
            'Trabalha com logística. Disponível para tarefas de transporte.',
    },
    {
        id: 9,
        nome: 'Isabela',
        sobrenome: 'Mendes',
        idade: 23,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Rua das Flores',
        organizacao: 'Sociedade de Socorro',
        dataDeBatismo: '2008-12-05',
        descricao:
            'Líder de grupo. Demonstra forte capacidade de organização e liderança.',
    },
    {
        id: 10,
        nome: 'Lucas',
        sobrenome: 'Carvalho',
        idade: 23,
        sexo: 'Masculino',
        endereco: 'Bairro Guarani, Estrada Velha',
        organizacao: 'Rapazes',
        dataDeBatismo: '2008-11-01',
        descricao:
            'Interessado em esportes e atividades ao ar livre. Ótimo com planejamento de lazer.',
    },
    {
        id: 11,
        nome: 'Mariana',
        sobrenome: 'Gomes',
        idade: 23,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Novo Lote',
        organizacao: 'Sociedade de Socorro',
        dataDeBatismo: '2008-08-15',
        descricao:
            'Disponível para auxílio nos estudos bíblicos. Mora próximo à capela.',
    },
    {
        id: 12,
        nome: 'Pedro',
        sobrenome: 'Martins',
        idade: 23,
        sexo: 'Masculino',
        endereco: 'Bairro Guarani, Próximo ao Colégio',
        organizacao: 'Rapazes',
        dataDeBatismo: '2008-05-20',
        descricao:
            'Tem habilidades em carpintaria. Pode ajudar em pequenos reparos na organização.',
    },
    {
        id: 13,
        nome: 'Rafaela',
        sobrenome: 'Lima',
        idade: 23,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Conjunto A',
        organizacao: 'Moças',
        dataDeBatismo: '2009-02-14',
        descricao:
            'Recém-chegada à organização. Muito engajada nas reuniões semanais.',
    },
    {
        id: 14,
        nome: 'Thiago',
        sobrenome: 'Souza',
        idade: 23,
        sexo: 'Masculino',
        endereco: 'Bairro Guarani, Rua Principal',
        organizacao: 'Quórum de Elderes',
        dataDeBatismo: '2008-03-30',
        descricao:
            'Contador por profissão. Ajuda com a tesouraria da organização.',
    },
    {
        id: 15,
        nome: 'Vitória',
        sobrenome: 'Fernandes',
        idade: 23,
        sexo: 'Feminino',
        endereco: 'Bairro Guarani, Rua do Bosque',
        organizacao: 'Sociedade de Socorro',
        dataDeBatismo: '2008-07-05',
        descricao:
            'Líder de jovens na sua região. Forte foco em mentoria e desenvolvimento pessoal.',
    },
];

export default membros;
